name: Progress Bar CI

on:
  [push]
#   workflow_dispatch:
#   schedule:
#     - cron: '0 */1 * * *'
# git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Update README.md
      run: node index.js > README.md
    - name: Commit change 
      run: |
          git config user.name 'github-actions[bot]'
          git config user.email '1129697645+github-actions[bot]@users.noreply.github.com'
          git commit -m "bot: update README.md automatically"
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
